controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda_jtc_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_jtc_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
        #gains:
        #panda_joint1: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint2: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint3: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint4: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint5: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint6: { p: 500., d: 1., i: 0., i_clamp: 1. }
        #panda_joint7: { p: 500., d: 1., i: 0., i_clamp: 1. }

